version: '3'
services:

  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "/RESTLibrary/bin/migrate up && /RESTLibrary/bin/api" ]

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=restlibrary_db
      - POSTGRES_USER=restlibrary_user
      - POSTGRES_PASSWORD=restlibrary_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U restlibrary_user -d restlibrary_db" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always